<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6hkqQ3G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6hkqQ3G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6hkqQ3G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6hkqQ3G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6hkqQ3G\App_KernelDevDebugContainer([
    'container.build_hash' => '6hkqQ3G',
    'container.build_id' => 'a1c7d8fe',
    'container.build_time' => 1765713757,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6hkqQ3G');
